- README.md
> add fireward

- README.md
- README_RU.md
Hi James,
please, consider my proposal to add the Firebase Status Dashboard to the official nodes.
I understand that this is not necessary, but it is convenient for me to refer to the awesome list during my consultations and my training and this is really useful.
> Add a new item

- README.md
Boilerplate for React developers who want to quick start a project in Firebase
> add Nextbase

- README.md
[Firestore Query Browser](https://firestore-query-browser.firebaseapp.com) - WebApp to Query, (Batch-)Edit & Export documents with app & user switching.
> Add Firestore Query Browser

- README.md
- extensions
- app distribution
- firebase summit YT
> Firebase summit 2019 announcements!

- README.md
Add Facebook link to the Follow section & Firebase Summit 2019 playlist link to the Other section
> Add Facebook link & Firebase Summit 2019 playlist

- readme.md
- readme_ru.md
Add [asdf-firebase](https://github.com/jthegedus/asdf-firebase)
> feat: asdf-firebase plugin

- readme.md
Added firebase-kotlin-sdk to new releases - not sure which is best section since its multiplatform
> add: firebase-kotlin-sdk

- .github/ISSUE_TEMPLATE/suggestion.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> fix: PR and Issue templates

- readme.md
---
name: Corrections, Additions, Updates or Removals
about: PRs of all kinds are welcome to Awesome Firebase
title: ""
labels: ""
---
The event page contains session and speaker detail week wise. Also there's link for each session to watch on-demand on YouTube. Session related content and code-labs can be found in resource tab.
> add: event link of Firebase Live 2020

- readme_ru.md
Signed-off-by: Alex Ivanov <ai@contributor.pw>
---
name: Corrections, Updates
about: PRs of translates flow
title: "Updates. Russian"
labels: "Translation"
---
```
```
The big translation for a long time. I haven't had the opportunity to do this before.
> docs: russian translation updates

- readme.md
---
name: Additions
about: Add Refi tool
title: ""
labels: ""
---
- [x ] is the source `https`?
- [ x] is the source valid ([would not lead a beginner astray](../../CONTRIBUTING.md#valid-sources))?
- [ x] have you included the appropriate [legend emoji](../../README.md#legend)?
- [ x] the item has the following format:
```
```
Add Refi tool to the awesome list
> docs: add Refi App

- readme.md
---
name: Corrections, Additions, Updates or Removals
about: PRs of all kinds are welcome to Awesome Firebase
title: ""
labels: ""
---
```
```
> feat: Firefoo GUI client to CLI & Editor

- readme.md
- readme_ko.md
- readme_ru.md
---
name: Additions
about: PRs of translates flow
title: "Additions Korean"
labels: "Translation"
---
```
```
I did a Korean translation. 
I hope this helps you. 
Please consider approving it.
Thank you.
> feat: KO translations

- readme_ko.md
---
name: Corrections
about: PRs of all kinds are welcome to Awesome Firebase
title: ""
labels: ""
---
```
```
Fixed my ko.md syntax, typo.
Thanks.
> fix: ko.md syntax, typo

- readme.md
---
name: Additions
about: Adds Firebase Extension for Typesense for full-text search
title: ""
labels: ""
---
Adds Firebase Extension for Typesense for full-text search
```
```
> feat: add Typesense Firebase extension

- .github/workflows/lint.yml
Remove the deprecated Ruby GitHub Action
> ci: remove deprecated ruby action

- readme.md
> Our team decided to pause this project, and please DON'T use it.
> fix: drop unmaintained product

- readme-ko.md
- readme-ru.md
> fix: update dependent drop unmaintained product #69

- readme.md
> feat: unofficial php admin sdk

- readme.md
Fireship is underrated in this document IMO. His channel is a must-know, to every Firebase loving, Web developer.
> docs: add fireship.io bio

- readme.md
> docs: add firelordJS

- readme-ko.md
- readme-ru.md
- readme.md
old title:
new title with updated url:
> correct path to workflow badge

- readme.md
[Dynaboard](https://dynaboard.com/) is a collaborative low-code web app IDE that lets devs create applications from Firebase and other data sources.
In a couple of clicks, [Dynaboard's AI](https://dynaboard.com/blog/dynaboard-ai) generates relevant UI components and filtering functions from the underlying data.
> Adding Dynaboard to the Other section.
